-- With the help of ChatGP

-- List all artworks currently on display, with the artist name and room information
SELECT a.pieceID, a.title, p.name AS artistName, r.roomNumber, r.floor
FROM ArtWork a
JOIN Artist ar ON a.artistID = ar.artistID
JOIN Person p ON ar.personID = p.personID
JOIN Room r ON a.roomID = r.roomID
WHERE a.state = 'InUse';

-- Daily summary of visits: number of visits, total visitors and average party size
SELECT visitDate, COUNT(*) AS numVisits, SUM(partySize) AS totalVisitors, AVG(partySize) AS avgPartySize
FROM Visit
GROUP BY visitDate
ORDER BY visitDate;

-- Total revenue generated by each visit pack, considering party size and discount
SELECT vp.packID, vp.name, SUM(v.partySize * vp.price * (1 - IFNULL(v.discount, 0))) AS totalRevenue
FROM Experience e
JOIN Visit v     ON e.visitID = v.visitID
JOIN VisitPack vp ON e.packID = vp.packID
GROUP BY vp.packID, vp.name
ORDER BY totalRevenue DESC;


-- List all events that are currently active (today between startDate and endDate)
SELECT eventID, theme, startDate, endDate
FROM Event
WHERE date('now') BETWEEN startDate AND endDate
ORDER BY startDate;


-- Average feedback rating per visit pack and number of feedback entries
SELECT vp.packID, vp.name, AVG(f.packRating) AS avgRating, COUNT(*) AS numFeedbacks
FROM Experience e
JOIN VisitPack vp ON e.packID = vp.packID
JOIN Feedback f   ON e.feedbackID = f.feedbackID
GROUP BY vp.packID, vp.name
ORDER BY avgRating DESC;


-- Artworks that were marked as favourite more often by visitors
SELECT a.pieceID, a.title, COUNT(*) AS timesFavourited
FROM Favourite fav
JOIN ArtWork a ON fav.pieceID = a.pieceID
GROUP BY a.pieceID, a.title
ORDER BY timesFavourited DESC;


